# https://starship.rs/config/

add_newline = false

[package]
disabled = true

[directory]
style = "bold blue"

[git_branch]
style = "bold white"

[git_status]
style = "bold white"
ahead.style = "purple"
ahead.value =""
behind.style = "cyan"
behind.value = ""
conflicted.style = "yellow"
deleted.style = "black"
diverged.style = "purple"
diverged.value = ""
modified.style = "red"
modified.value = "*"
renamed.style = "purple"
staged.style = "green"
staged.value = "+"
stashed.style = "yellow"
untracked.style = "cyan"

[git_commit]
disabled = false
style = "bold black"
prefix = ""
suffix = " "

[ruby]
symbol = " "
